SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO AS I, FISH_NAME_INFO AS N
WHERE I.FISH_TYPE = N.FISH_TYPE
  AND I.LENGTH = (
    SELECT MAX(FI.LENGTH)
    FROM FISH_INFO FI
    WHERE FI.FISH_TYPE = I.FISH_TYPE
  )
ORDER BY I.ID ASC;